poor quality tasks
ISUCT/Tprogramming_2021 pull request #24
Opened 2021-10-05 20:58 UTC by DaniilOykin

2021-10-08 06:51 UTC, alexthvest requested changes

2021-10-09 07:51 UTC, jskonst requested changes

2021-10-09 07:51 UTC, jskonst commented on CourseApp.Tests/CalcTest.cs
> +
let's use inlineData for multiple tests

2021-10-09 07:51 UTC, jskonst commented on CourseApp/Equation.cs
> +            while (xn <= xk)
i would prefer to use for loop - it's much saftier

2021-10-09 07:51 UTC, jskonst commented on CourseApp/Equation.cs
> +            double[] results = new double[(int)(((xk - xn) / dx) + 1)];
Please add test case where xn will be greater than xk

2021-10-09 07:51 UTC, jskonst commented on CourseApp/Program.cs
> +            // Console.WriteLine($"Возраст мыши: {new_mouse.Age}.");
Please NEVER upload commented code

2024-07-03 14:49 UTC, closed without merging